### PR TITLE
Create image.py

### PR DESCRIPTION
**Pull request by hemant933**
add image option at whiteboard

### CODE REVIEW

**Comment by asmit203** [comment]
please PR to DEV branch

**Review by asmit203 — APPROVED** [review]
machine approval

**Comment by asmit203** [comment]
@hemant933 recheck it please

**Comment by hemant933** [comment]
can u plz allot me the points under codepeak

**Comment by asmit203** [comment]
> can u plz allot me the points under codepeak

The image pasting was not working and I by mistake merged it for a small amount of time and it was reverted just after that please check [80](https://github.com/asmit203/TalkitOut/pull/80)
I wasnt able to get it working hence reverted the merge

**Pull request merged**
